services:
    node:
        build: .
        container_name: ${MODE}
        ports:
            - ${PORT}:${PORT}
        expose:
            - ${PORT}
        environment:
            - SERVER_URL
            - DOMAIN
            - PORT
            - PROJECT
            - MODE=production
