name: Deploy to Railway

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build Artifact Project
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Configure GitHub Actions
        uses: actions/checkout@v3

      - name: 🛠 Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.7

      - name: 🚧 Install dependencies and Build project
        run: pnpm install --no-frozen-lockfile && pnpm run build

      - name: 🏷 Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist/
            Dockerfile
            pnpm-lock.yaml
            package.json

  publish:
    name: Build and Push Image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 🏷 Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: 🚀 Deploying to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}